### ISSUE TITLE
Broken links to U-boot in Readme

### ISSUE THREAD

**Issue by SondreNjaastad** [varigit/uboot-imx#11]
The links to the U-Boot repository is broken 

In default branch

Permalink:
https://github.com/varigit/uboot-imx/blob/2d1855ccbf780293405ade91894011708531f443/README#L63

and

https://github.com/varigit/uboot-imx/blob/2d1855ccbf780293405ade91894011708531f443/README#L62

**Comment by varigigi** [comment]
Hi @SondreNjaastad,
we appreciate if you could provide indications about
- branch
- files
- lines

Thanks
Best Regards
Pier

**Comment by SondreNjaastad** [comment]
Hi @varigigi 

Updated the issue. Also submited suggestion for fix

Best regards

**Comment by varigigi** [comment]
Hi @SondreNjaastad,
on February 2021, Denx pushed a comprehensive patch, but only for new releases and never backported
    https://source.denx.de/u-boot/u-boot/-/commit/a3bbd0b912f9afff745247fe9641961875322926
We will discuss this issue internally and will get back to you.

**Comment by varigigi** [comment]
Hi @SondreNjaastad,
as explained in the pull request, we decided to be aligned to Denx behavior and don't merge this.
Thanks
Best Regards
Pier
