### ISSUE TITLE
u-boot-spl section rodata will not fit in region sram

### ISSUE THREAD

**Issue by vinifr** [varigit/uboot-imx#3]
I am getting this error when trying to compile u-boot branch _imx_v2017.03_4.9.11_1.0.0_ga_var01_

_arm-linux-gnueabihf-ld.bfd: u-boot-spl section `.rodata' will not fit in region `.sram'
arm-linux-gnueabihf-ld.bfd: region `.sram' overflowed by 5976 bytes
scripts/Makefile.spl:304: recipe for target 'spl/u-boot-spl' failed_

**Comment by eranmati** [comment]
Hi @vinifr .
I can't reproduce your issue.
Which compiler are you using?
Did you make any changes to the code?
Please see the following:
http://variwiki.com/index.php?title=Yocto_Build_U-Boot&release=RELEASE_ROCKO_V1.2_VAR-SOM-MX6

Next time, please open a ticket in the Variscite customer portal:
https://varisciteportal.axosoft.com/

Regards,
Eran

**Comment by vinifr** [comment]
Hi @eranmati ,
"Which compiler are you using?" gcc-arm-linaro-4.9.4
"Did you make any changes to the code?" Not.

I followed the steps from link you pointed out, but I am not using yocto compiler, i am using linaro cross compiler. [https://releases.linaro.org/components/toolchain/binaries/4.9-2017.01/](url)

$ git clone https://github.com/varigit/uboot-imx.git -b imx_v2017.03_4.9.11_1.0.0_ga_var01
$ cd uboot-imx
$ make mx6var_som_sd_defconfig
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

imx_v2015.10_dart_6ul_var1 branch works though.

**Comment by eranmati** [comment]
In our Debian Stretch release we use the following Linaro toolchain and I can't reproduce your issue with it, either: http://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/arm-linux-gnueabihf/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf.tar.xz

See:
http://variwiki.com/index.php?title=Debian_Build_Release&release=RELEASE_STRETCH_V1.0_VAR-SOM-MX6

(and the Yocto Rocko gcc version is 7.2/7.3)

I suggest you upgrade your toolchain - using one of the aforementioned toolchains we work with would be best.

Regards,
Eran

**Comment by vinifr** [comment]
Really strange. It looks like any version < 6.3 does not work. I tested 5.5.0, does not work either. But 6.3 works. 
Thanks for your help.
