### ISSUE TITLE
i.MX8M Mini DART support is missing in imx_v2020.04_5.4.24_2.1.0_var01

### ISSUE THREAD

**Issue by zandrey** [varigit/uboot-imx#5]
Branch `imx_v2020.04_5.4.24_2.1.0_var01` cannot be built for _DART-MX8M-MINI_ module and EVK, as it appears that the support for it is currently not present.

This support has been introduced on the branch `imx_v2019.04_4.19.35_1.1.0-var01` in commit [13f59fa819d2375279103d19c7f4911ddfd41552], but it is neither ported nor present on the `imx_v2020.04_5.4.24_2.1.0_var01` branch.

_meta-freescale_ has NXP release `5.4.24_2.1.0` integrated on the _dunfell_ branch, which contains the U-Boot version `imx_v2020.04_5.4.24_2.1.0` from NXP.

As a consequence, missing _DART-MX8M-MINI_ support in the U-Boot makes it impossible to build _dunfell_ release.

Are there any plan to merge the support for _DART-MX8M-MINI_ into `imx_v2020.04_5.4.24_2.1.0_var01`?

Thanks a lot!

-- andrey

**Comment by eranmati** [comment]
Hi Andrey.
We will make a DART-MX8M-MINI release based on NXP's recent L5.4.47_2.2.0​​ release.

Next time, please use the Variscite customer portal:
https://varisciteportal.axosoft.com/

Regards,
Eran

**Comment by zandrey** [comment]
Hello @eranmati 

Thanks for your clarifications here.

> We will make a DART-MX8M-MINI release based on NXP's recent L5.4.47_2.2.0​​ release.

Please note, that `L5.4.47_2.2.0​​` is not yet planned to be made part of `dunfell` release, therefore with this decision you're currently waving a support for _DART-MX8M-MINI_ on Yocto LTS branch.

> 
> Next time, please use the Variscite customer portal:
> https://varisciteportal.axosoft.com/

Sure, thanks a lot for your guidance! I would definitely use a Customer support portal to address this issue further.

> 
> Regards,
> Eran

-- andrey

**Comment by eranmati** [comment]
As updated on the customer portal, we will release Yocto Dunfell soon.

Regards,
Eran
