### ISSUE TITLE
UBoot support for VAR-SOM-MX8M-MINI

### ISSUE THREAD

**Issue by RuhanSA079** [varigit/uboot-imx#7]
Hello. Can you add support for the MX8M-Mini SOM?

I am trying to build a custom Ubuntu Core image for this SOM to be flashed on the eMMC of the SOM.

My u-boot compilation fails with
make[1]: *** No rule to make target 'fsl-imx8mm-var-som.dtb', needed by 'u-boot-lpddr4-ddr4-evk.itb'.  Stop.

There is no listed fsl-imx8mm-var-som.dtb in the arch/arm/dts directory?
Do I need the latest U-boot sources to do this? I'm attempting to build with the debian bullseye script (imx8mm-var-dart)
Thanks.

**Comment by RuhanSA079** [comment]
Found the commit adding support for the module, closing.

**Comment by eranmati** [comment]
Hi @RuhanSA079 
Please see:
https://variwiki.com/index.php?title=VAR-SOM-MX8M-MINI

And for the currently latest U-Boot branch with VAR-SOM-MX8M-MINI support:
https://variwiki.com/index.php?title=Yocto_Build_U-Boot&release=RELEASE_DUNFELL_V1.1_DART-MX8M-MINI

Regards,
Eran
