### ISSUE TITLE
`arch_preboot_os':

### ISSUE THREAD

**Issue by loulansuiye** [varigit/uboot-imx#8]
LD      u-boot
arch/arm/mach-imx/built-in.o: In function `arch_preboot_os':
/home/atris/dev/src/kernel/uboot-imx-imx_v2020.04_5.4.47_2.2.0_var01/arch/arm/mach-imx/cpu.c:335: undefined reference to `ldo_mode_set'
drivers/built-in.o: In function `mxs_of_get_timings':
/home/atris/dev/src/kernel/uboot-imx-imx_v2020.04_5.4.47_2.2.0_var01/drivers/video/mxsfb.c:458: undefined reference to `video_link_get_next_device'
/home/atris/dev/src/kernel/uboot-imx-imx_v2020.04_5.4.47_2.2.0_var01/drivers/video/mxsfb.c:460: undefined reference to `video_link_get_display_timings'
arm-linux-gnueabihf-ld.bfd: BFD (Linaro_Binutils-2019.12) 2.28.2.20170706 assertion fail /home/tcwg-buildslave/workspace/tcwg-make-release_1/snapshots/binutils-gdb.git~users~linaro~binutils-2_28-branch/bfd/elf32-arm.c:9514
arm-linux-gnueabihf-ld.bfd: BFD (Linaro_Binutils-2019.12) 2.28.2.20170706 assertion fail /home/tcwg-buildslave/workspace/tcwg-make-release_1/snapshots/binutils-gdb.git~users~linaro~binutils-2_28-branch/bfd/elf32-arm.c:9514
arm-linux-gnueabihf-ld.bfd: BFD (Linaro_Binutils-2019.12) 2.28.2.20170706 assertion fail /home/tcwg-buildslave/workspace/tcwg-make-release_1/snapshots/binutils-gdb.git~users~linaro~binutils-2_28-branch/bfd/elf32-arm.c:9514
make: *** [Makefile:1701: u-boot] Error 1

**Comment by varigigi** [comment]
@loulansuiye , can you please clarify the context?
For some reason you are apparently trying to compile a uboot version supporting only  DART/VAR-SOM-MX8M-PLUS (64 bits) with a 32 bits compiler.
Thanks
BR
Pier

**Comment by varigigi** [comment]
Hi @loulansuiye,
I'm now closing this issue as not reproducible using the right GCC.
Best Regards
Pier
