### ISSUE TITLE
U-Boot support LVDS dual channel

### ISSUE THREAD

**Issue by StefanLellwitz** [varigit/uboot-imx#9]
Hi,

I am building U-Boot for VAR-SOM-MX8.
I would like to add a second LVDS channel to support a custom dual channel LVDS Display.
I tried to extend the [Device Tree](https://github.com/varigit/uboot-imx/blob/a868ae6fd152900443f4f027835c573fa980de4e/arch/arm/dts/fsl-imx8qm-var-som.dts#L332) like this:

```
&ldb1 {
	status = "okay";

	lvds-channel@0 {
		fsl,data-mapping = "jeida";
		fsl,data-width = <24>;
		status = "okay";
		primary;

		display-timings {
			native-mode = <&timing0>;

			timing0: timing {
				clock-frequency = <70930000>;
				hactive = <960>;
				vactive = <1080>;
				hback-porch = <53>;
				hfront-porch = <52>;
				vback-porch = <15>;
				vfront-porch = <15>;
				hsync-len = <48>;
				vsync-len = <3>;
			};
		};
	};
	
	lvds-channel@1 {
		fsl,data-mapping = "jeida";
		fsl,data-width = <24>;
		status = "okay";

		display-timings {
			native-mode = <&timing1>;

			timing1: timing {
				clock-frequency = <70930000>;
				hactive = <960>;
				vactive = <1080>;
				hback-porch = <53>;
				hfront-porch = <52>;
				vback-porch = <15>;
				vfront-porch = <15>;
				hsync-len = <48>;
				vsync-len = <3>;
			};
		};
	};
};
```
But the custom Display doesn't show anything (except for backlight) and U-Boot returns:
<pre>
U-Boot 2020.04-imx_v2020.04_5.4.24_2.1.0_var02+ga868ae6fd1 (Mar 14 2021 - 10:21:37 +0000)

CPU:   NXP i.MX8QM RevB A53 at 1200 MHz at 37C

Model: Variscite VAR-SOM-MX8
Boot:  SD1
DRAM:  4 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... *** Warning - bad CRC, using default environment

[*]-Video Link 0 (960 x 1080)
        [0] dpu@56180000, video
        <b>[1] lvds-channel@0, display</b>
Error (-1): cannot determine file size
In:    serial
Out:   serial
Err:   serial
</pre>
So it seems that U-Boot does not recognize the second LVDS channel.
But why?

**Comment by myhalici** [comment]
did you solve it?
(same for me.)

**Comment by StefanLellwitz** [comment]
No, we did not track this any further, as we moved away from the product. But looking ahead, I would still also be interested in a solution.

**Comment by myhalici** [comment]
> No, we did not track this any further, as we moved away from the product. But looking ahead, I would still also be interested in a solution.

Here my config for dual channel 1920x720 display 

`panel_lvds: panel-lvds {
		compatible = "panel-lvds";
		backlight = <&backlight>;
		width-mm = <292>;
		height-mm = <109>;
		label = "am-480272h3tmqw-t01h";
		data-mapping = "vesa-24";
		data-width = <24>;
		panel-enable-delay = <55>;
		panel-prepare-delay = <50>;
                panel-disable-delay = <20>;
                panel-unprepare-delay = <80>;
		status = "okay";

		panel-timing {
			clock-frequency = <45000000>;
			hactive = <960>;
			vactive = <720>;
			hback-porch = <31>;
			hfront-porch = <0>;
			vback-porch = <70>;
			vfront-porch = <0>;
			hsync-len = <1>;
			vsync-len = <2>;
			hsync-active = <0>;
			vsync-active = <1>;
			de-active = <1>;
			pixelclk-active = <1>;
		};


		ports {
		      	#address-cells = <1>;
		        #size-cells = <0>;
			port@1 {
          			reg = <1>;
				panel_in0: endpoint {
					remote-endpoint = <&lvds_out0>;
				};
			};
			port@2 {
          			reg = <2>;
				panel_in1: endpoint {
					remote-endpoint = <&lvds_out1>;
				};
			};
		};
	};


`

and

`
&ldb1 {
	compatible = "fsl,imx8qxp-ldb";
	//power-domains = <&pd IMX_SC_R_LVDS_0>;
	status = "okay";
	fsl,split-mode;
	lvds-channel@0 {
		reg = <0>;
		crtc = "ipu2-di1";
		fsl,data-mapping = "spwg";
		fsl,data-width = <24>;
		status = "okay";

 		/*display-timings {
 			native-mode = <&timing0>;
 			timing0: AM-1920720B4TZQW-12H {
				clock-frequency = <45000000>;
				hactive = <960>;
				vactive = <720>;
				hback-porch = <15>;
				hfront-porch = <15>;
				vback-porch = <35>;
				vfront-porch = <35>;
				hsync-len = <20>;
				vsync-len = <20>;
 			};
 		};*/
 		
		port@1 {
			reg = <1>;

			lvds_out0: endpoint {
				remote-endpoint = <&panel_in0>;
			};
		};
	};
	lvds-channel@1 {
		reg = <1>;
		crtc = "ipu1-di0";
		fsl,data-mapping = "spwg";
		fsl,data-width = <24>;
		status = "okay";
		primary;

 		/*display-timings {
 			native-mode = <&timing1>;
 			timing1: am-480272h3tmqw-t01h {
				clock-frequency = <45000000>;
				hactive = <960>;
				vactive = <720>;
				hback-porch = <15>;
				hfront-porch = <15>;
				vback-porch = <35>;
				vfront-porch = <35>;
				hsync-len = <20>;
				vsync-len = <20>;
 			};
 		};*/
 		
		port@2 {
			reg = <2>;

			lvds_out1: endpoint {
				remote-endpoint = <&panel_in1>;
			};
		};
	};
};

&ldb2_phy {
	status = "disabled";
};

&ldb2 {
	status = "disabled";
};
`


it works for me.

**Comment by StefanLellwitz** [comment]
@myhalici Thanks for sharing your config. I will try this out as soon as I find some time for it.

**Comment by varigigi** [comment]
Hi @StefanLellwitz and @myhalici,
assuming you are fine, we are now closing this issue.
Best Regards
Pier
